name: On Merge

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Dotnet Build
      run: dotnet build --configuration Release ./GarcissNetLibs/Garciss.Net.Libs.sln

    - name: Generar nuspec
      run: |
        ls NugetPackages/PackagesCompilaciones/netstandard2.1
        cd NugetPackages/NugetConfig/
        .\nuspecGeneratorNetCoreNetStandard.ps1
      shell: powershell
    

    - name: Nuget Pack para preparar el paquete
      run: |
        ls NugetPackages/PackagesCompilaciones/netstandard2.1
        cd NugetPackages/NugetConfig/
        nuget pack Garciss.Net.Libs.nuspec -Verbosity Detail
        
    - name: Push generated package to GitHub registry
      run: |
        cd NugetPackages/NugetConfig/
        nuget push *.nupkg ${{ secrets.USER_TOKEN_GITHUB_PACKAGE }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
        
